# -*- makefile -*-
#
# misc applets that didn't seem to be specific to any wm

#DCWING_NAME=dcwing
#DCWING_VERSION=1.10
#DCWING_TAR=$(DCWING_NAME).tgz
#DCWING_URL=http://worldserver.oleane.com/rsn/Archives/$(DCWING_TAR)

#APPLET_LIST += DCWING

#LCD_NAME=lcd
#LCD_VERSION=1.10
#LCD_TAR=$(LCD_NAME).tar.gz
#LCD_URL=http://worldserver.oleane.com/rsn/Archives/$(LCD_TAR)

#APPLET_LIST += LCD

MIXER.APP_NAME=Mixer.app
MIXER.APP_VERSION=1.8.0
MIXER.APP_TAR=$(MIXER.APP_NAME)-$(MIXER.APP_VERSION).tar.gz
MIXER.APP_URL=http://www.fukt.bth.se/~per/mixer/$(MIXER.APP_TAR)

APPLET_LIST += MIXER.APP

SALMON_NAME=salmon
SALMON_VERSION=1.2.2
SALMON_TAR=$(SALMON_NAME)-$(SALMON_VERSION).tar.gz
SALMON_URL=http://tigr.net/afterstep/download/salmon/$(SALMON_TAR)

APPLET_LIST += SALMON

TEMPERATURE.APP_NAME=Temperature.app
TEMPERATURE.APP_VERSION=1.4
TEMPERATURE.APP_TAR=$(TEMPERATURE.APP_NAME)-$(TEMPERATURE.APP_VERSION).tar.gz
TEMPERATURE.APP_URL=http://www.fukt.bth.se/~per/temperature/$(TEMPERATURE.APP_TAR)

APPLET_LIST += TEMPERATURE.APP

