#!/usr/bin/perl

use strict;

if (-e "/etc/mandrake-release") {
    # from mandrake push SRPMS and MDK RPMS
    #
    system("make mdk-i586");
    system("rsync -avP -e ssh --delete-after --delete-excluded SRPMS/*.src.rpm afterstep\@spring.webconquest.com:~/www.afterstep.org/rpms/SRPMS/");

    system("rsync -avP -e ssh --delete-after --delete-excluded RPMS/i586/*.rpm RPMS/i586/*cz afterstep\@spring.webconquest.com:~/www.afterstep.org/rpms/RPMS/mdk/10.1/i586/");
} elsif (-e "/etc/redhat-release") { 
    system("make fc3-i386");
    system("rsync -avP -e ssh --delete-after --delete-excluded RPMS/i386/*.rpm afterstep\@spring.webconquest.com:~/www.afterstep.org/rpms/RPMS/fc/3/i386/");
}


