#!/usr/bin/perl


use strict;

my %distros = (
    mdk => {
	meta => "mdk-i586",
	rpms => "RPMS/i586/",
	srpms => "SRPMS/*.src.rpm",
	target => "RPMS/mdk/10.1/i586/",
    },
    fc => {
	meta => "fc3-i386",
	rpms => "RPMS/i386/",
	target => "RPMS/fc/3/i386/",
    },
);

my $rsyncopts = "-avP -e ssh --delete-after --delete-excluded";
my $target = "davemann\@ftp.afterstep.org:~/fao/stable/rpms";
my $distro = shift;

if($distros{$distro}) {
    print "Processing distro $distro\n";
    my $h = $distros{$distro};
    system("make $h->{meta}");
    system("rsync $rsyncopts $h->{rpms}/* $target/$h->{target}");
    if($h->{srpms}) {
	system("rsync $rsyncopts $h->{srpms} $target/SRPMS");
    }
} else {
    print "Nothing to do for distro $distro\n";
}

